# docker requires superuser permissions
sudo: required

# tells Travis that we need a copy of the Docker CLI
services:
   - docker

# commands that get executed before the tests or the deployment occur
before_install:
   # tells Travis CI to build the image using the "Dockerfile.dev" file.
   # PS: it is best practice to tag (-t) the image. 
   - docker build -t brennobiwan/docker-react -f Dockerfile.dev .

# this is where we run some scripts to actually execute the tests.
script:
   # the "-- --coverate" enforces the test suite to exit after it is done.
   # PS: it is needed because Travis CI requires an exit code, so the test needs to finish; 
   # the test suite prompts for an input to keep testing, by default.
   - docker run -e CI=true brennobiwan/docker-react npm run test -- --coverage
