# docker requires superuser permissions
sudo: required

# tells Travis that we need a copy of the Docker CLI
services:
   - docker

# commands that get executed before the tests or the deployment occur
before_install:
   # tells Travis CI to build the image using the "Dockerfile.dev" file.
   # PS: it is best practice to tag (-t) the image. 
   - docker build -t brennobiwan/docker-react .

# this is where we run some scripts to actually execute the tests.
#script:
   # the "-- --coverage" enforces the test suite to exit after it is done.
   # PS: it is needed because Travis CI requires an exit code, so the test needs to finish; 
   # the test suite prompts for an input to keep testing, by default.
   #- docker run -e CI=true brennobiwan/docker-react npm run test -- --coverage

language: generic

# this section tells Travis how to deploy our container on AWS Beanstalk. 
deploy: 
   edge: true
   # Travis CI comes pre-configured to deploy the app on some providers.
   provider: elasticbeanstalk
   # defines the region in which our elastic beanstalk instance was created;
   # PS: this can be seen from the Elastic Beanstalk instance URL.
   region: "us-east-1"
   # name of the application.
   name: "docker-react"
   # name of the environment; it is the app's name dash "env".
   env: "Dockerreact-env"
   # name of the s3 bucket into which Travis will store all our GitHub files.
   # Once Travis decides to deploy the code, it will zip all files into one and save it on an s3 bucket, then
   # it saves that file into an s3 bucket, which will trigger elasticbeanstalk to deploy that code.
   # PS: the s3 bucket is automatically created along with the Elastic Beanstalk instance.
   bucket_name: "elasticbeanstalk-us-east-1-185170745503"
   # path to the app you're building inside s3; needed because the bucket is re-used by your other instances.
   bucket_path: "docker-react"
   # triggers the deployment section of Travis only when the master branch is updated.
   on:
      branch: master
   # using secret environment for security purposes; the actual keys are stored in travis-ci.com
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: 
      secure: $AWS_SECRET_KEY



